version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1.6

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint:
        filters:
          tags:
            only: /^v.*/
      - plugin-ci/test:
        filters:
          tags:
            only: /^v.*/
      - plugin-ci/build:
        filters:
          tags:
            only: /^v.*/
      - plugin-ci/deploy-release-github:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
        requires:
          - plugin-ci/lint
          - plugin-ci/test
          - plugin-ci/build
